# Generated by Django 5.1.1 on 2024-10-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_category_options_event_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_group',
            field=models.IntegerField(choices=[(10, 'Big'), (2, 'Small')], default=2),
            preserve_default=False,
        ),
    ]
